default:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "kingdom_rush_user"
    password: process.NODE_ENV.DB_PASSWORD
    database: "kingdom_rush_db"
    entities: ["dist/models/*.js", "src/models/*.ts"] # when running 'npm run build' you must remove "src/models/*.ts"
    #entities: ["dist/models/*.js"]
    logging: true
    synchronize: false
    dropSchema: false
    migrations: ["src/migrations/*.ts"]
    #migrations: ["dist/migrations/*.js"]
    cli:
        migrationsDir: "src/migrations"

test:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "test_user"
    password: "password"
    database: "test_db"
    entities: ["src/models/*.ts"]
    logging: false
    synchronize: true
    dropSchema: true
