default:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "kingdom_rush_user"
    password: process.NODE_ENV.DB_PASSWORD
    database: "kingdom_rush_db"
    entities: ["dist/entity/*.js", "src/entity/*.ts"]
    logging: false
    synchronize: true
    dropSchema: true

test:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "test_user"
    password: "password"
    database: "test_db"
    entities: ["src/entity/*.ts"]
    logging: false
    synchronize: true
    dropSchema: true
