default:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "kingdom_rush_user"
    password: process.NODE_ENV.DB_PASSWORD
    database: "kingdom_rush_db"
    entities: ["dist/models/*.js"]
    logging: true
    synchronize: false
    dropSchema: false
    migrations: ["src/migrations/*.js"]
    cli:
        migrationsDir: "migration"

test:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "test_user"
    password: "password"
    database: "test_db"
    entities: ["src/models/*.ts"]
    logging: false
    synchronize: true
    dropSchema: true
